import type { Metadata } from "next";
import ControlPanel from "../_components/control-panel/controlPanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ControlPanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ControlPanel>{children}</ControlPanel>;
}
