import type { Metadata } from "next";
import Header from "../_components/header";
import Footer from "../_components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const HomeLayout = ({children}: Readonly<{children: React.ReactNode}>) => {
  return (
    <>
    <Header />
    {children}
    <Footer />
    </>
  )
}

export default HomeLayout