import type { Metadata } from "next";
import App from "./app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <App>{children}</App>;
};

export default HomeLayout;
